version: '3.8'

services:
  web:
    build: ./app1
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - postgres_data1:/var/lib/postgresql/data # создаем волюм на уровне докер - /var/lib/docker/volumes
      - /app1/init_sql:/docker-entrypoint-initdb.d  # Монтируем скрипт инициализации

volumes: # создаем волюм на уровне докер - /var/lib/docker/volumes
  postgres_data1: